### PR TITLE
Little syntax-error

### PR DESCRIPTION
**Pull request by ReinhardtMedien**
<f:translate key="LLL:fileadmin/lang/locallang.xml:domain_model.bestfilm" arguments="{0: 'Back to the Future'}" />

behind Future -> ' added

### CODE REVIEW

**Comment by liayn** [comment]
Can you please redo the commit and review the typos in your commit message.
Liddle -> Little
addet -> added

Thanks

**Comment by ReinhardtMedien** [comment]
i would if i could, but...
can i edit my previous commit?
or how can i redo that?
i'm new to github... 
simply pushing again? from the typo3-doc ?

**Comment by marble** [comment]
@ReinhardtMedien The usual workflow is: You change something and commit that to a new branch. Then you push the branch and create a pull request from there. After that, you can push changes to your branch. These will automatically appear in the Pull Request. Thanks for contributing. Go ahead, send more!

**Comment by ReinhardtMedien** [comment]
ok thanks

**Pull request merged**
