### PR TITLE
Update Raw.rst

### PR DESCRIPTION
**Pull request by garvinhicking**
Current text is german, and a bit too "coloured" to be used in official documentation. ;)

### CODE REVIEW

**Comment by marble** [comment]
Very good - many thanks! Don't hesitate to do more :-)

**Comment by garvinhicking** [comment]
There are some more pages like these (i.e. https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Format/Date.html - my personal favourite that I use to get happy now and then by reading it). I assume the goal would be to have all documentation english, right?

**Comment by marble** [comment]
Exactly - everything should be english. To understand the background: We don't have "official" documentation for Extbase and Fluid, which is really bad. "official" has the meaning of being maintained by the documentation team. Stefan Frömken had taken those personal notes in german when he started with extbase. And since the need was really great we put that online having in mind that there were several volonteers who offered to do the translation. That got stuck. So it's great to have somebody like you who's adding to that. If you like to do more: Send more! If it helps, you can have write access to the repo. PS: I'm still hoping we can have Patrick Lobacher's and Michael Schams' great book online in the end: https://leanpub.com/typo3extbase-en That would be the perfect "official" documentation. Personally I find it's THE indispensable source of information.

**Comment by garvinhicking** [comment]
Yeah, that would be my followup-question. If there are negotiations to get any sort of "official" documentation like the great book online, then any possible effort to brush up the current docs would be a waste of time, and always inferior to that book.

What I'm wondering is that the ViewHelpers for example have a solid inline documentation in the TYPO3 source code. Wouldn't it be preferrable to extract that somehow to reduce redundancies?

(A possible issue could be version mismatches, if the docs use a recent v8 codebase but most people might use the LTS instead)

**Comment by marble** [comment]
_Viewhelpers:_ Claus Due generates the docs from the sources, which is great. But of course it would be much better to have that on the official pages: https://fluidtypo3.org/viewhelpers.html

Why don't we have it there? Well, the documentation team (euphemism) is veeery small with very little manpower.

_Negotiations:_ We don't have those negotiations at the moment. Last time I asked it was Oct. 2015 or so, IIRC. At that time the authors felt sad about having spent so much time and effort having gained so little money. So they wanted to give the Leanpub idea a try first. But maybe it's time now to ask them again. I could even think of a crowdfunding for this.

_Slack:_ A communication like that about the ebook version typically would take place on Slack nowadays. Maybe you will like to join? https://forger.typo3.org/slack You only need your browser for this.

**Comment by garvinhicking** [comment]
I see, I figured it'd be something like that. Wrote a book about a OSS software as well (Serendipity) and breaking down the effort to $/hr drives tears to your eyes. I wrote the book in german so nothing of it could be used for our official docs, and documentation is always something nagging.

Let me chew some time on this on how brushing up more of these files would be useful, or if I should spend the time more in trying to find a long-term solution and participating in that slack. :)

**Comment by marble** [comment]
Joining Slack is a nobrainer - just do it. It's similar to getting access to a forum where you can look around. I can't see any disadvantages or annoyances.

**Pull request merged**
