### PR TITLE
Hinweis zu addQueryString

### PR DESCRIPTION
**Pull request by macjohnny**

### CODE REVIEW

**Comment by macjohnny** [comment]
please backport it to 7.6, 6.2

**Comment by marble** [comment]
The text looks like an improvement, I just had a look at the diff and not at the whole page.
(1) The whole manual should be english - can you help translating?
(2) If I understand that correctly, the problem may be (page) cache flooding as well. Should that be described as well? -> -> -> security warning?

**Comment by macjohnny** [comment]
@marble 
(1) should i replace my addition with an english version?
(2) yes, i have already submitted this. could you change your comment to remove any preliminary disclosure?

**Comment by marble** [comment]
yes, english please. What do you think could be disclosed?

**Comment by macjohnny** [comment]
could you remove the (2) part of your comment please?

**Comment by marble** [comment]
Did that, but don't know why. It is a problem we want to point out, don't we?

**Comment by macjohnny** [comment]
it does not seem this issue will ever be fixed, so at least it should be documented

**Pull request merged**
