### PR TITLE
Add 404 page

### PR DESCRIPTION
**Pull request by sypets**

### CODE REVIEW

**Comment by DanielSiepmann** [comment]
I'll have to check the 404 implementation on server side, so we add the feature to check for further locations of 404. This way we have a fallback 404, which is right now the only one, and the possibility to add 404 pages for each manual to increase UX.

**Comment by sypets** [comment]
Yes, that sounds good. Having a dedicated 404 for individual manuals is a little more work but has the advantage that people that got stranded on a 404 page, can use the menu and search box - assuming they are already in the correct manual. Also, the 404 page can contain a little more specific information, like the link to ViewHelper ref for Extbase / Fluid guide or Link to "TYPO3 Explained" for FAL ref or security guide.

**Comment by DanielSiepmann** [comment]
I'm totally with you.

I've implemented this feature and merged your PR. Once rendered, it should appear here: https://docs.typo3.org/typo3cms/ExtbaseFluidBook/10-Outlook/4-Property-mapping3242.html as an example and of course here: https://docs.typo3.org/typo3cms/ExtbaseFluidBook/404.html

**Comment by DanielSiepmann** [comment]
Checked, everything is working as expected.

**Pull request merged**
